### ISSUE TITLE
how to rectify an Omni camera model?

### ISSUE THREAD

**Issue by zlbing** [ethz-asl/image_undistort#26]
I have a Omni camera, I want to know how to get a rectified image?
Thanks.

**Comment by ZacharyTaylor** [comment]
Currently tho code only supports pinhole cameras with radtan, equidistant or fov distortion. However, allowing the system to operate with wider fov cameras is an interesting problem. 

What model are you currently using for your camera, also how was the calibration done?

**Comment by zlbing** [comment]
@ZacharyTaylor we calibrate Omni camera model with kalibr tools. but we have no idea to get a good rectified image.

**Comment by ZacharyTaylor** [comment]
So this is probably far too late to be any use, but today I finally got around to supporting a large range of camera models including the omni model. See #36

**Comment by zlbing** [comment]
Thanks.
