### ISSUE TITLE
List package's dependency 

### ISSUE THREAD

**Issue by marco-tranzatto** [ethz-asl/image_undistort#28]
Hi @ZacharyTaylor ,

for people for have never used this node it might be helpful to know where to download dependencies (for now only "nlopt"). I imagine some people at RSL would spend some time to understand which "nlopt" package they should download.  After ARCHE I can add a brief section in the readme file with this info, if you agree.

Cheers,
Marco.

**Comment by ZacharyTaylor** [comment]
Good idea, I have never really liked the nlopt dep. Had a go at improving things in https://github.com/ethz-asl/image_undistort/pull/25/files
