### ISSUE TITLE
Error When use Stereo_info_node to show the camera info 

### ISSUE THREAD

**Issue by wang-yu-yang** [ethz-asl/image_undistort#60]
When using Stereo_info_node to display the corrected image information, I encountered the following error：

SUMMARY
========

PARAMETERS
 * /camera/stereo_info/cam0/cam_overlaps: [1]
 * /camera/stereo_info/cam0/camera_model: pinhole
 * /camera/stereo_info/cam0/distortion_coeffs: [0.07307789354996...
 * /camera/stereo_info/cam0/distortion_model: equidistant
 * /camera/stereo_info/cam0/intrinsics: [264.788182513580...
 * /camera/stereo_info/cam0/resolution: [848, 800]
 * /camera/stereo_info/cam0/rostopic: /camera/fisheye1/...
 * /camera/stereo_info/cam1/T_cn_cnm1: [[0.9999954918913...
 * /camera/stereo_info/cam1/cam_overlaps: [0]
 * /camera/stereo_info/cam1/camera_model: pinhole
 * /camera/stereo_info/cam1/distortion_coeffs: [0.08072112677213...
 * /camera/stereo_info/cam1/distortion_model: equidistant
 * /camera/stereo_info/cam1/intrinsics: [258.992611823673...
 * /camera/stereo_info/cam1/resolution: [848, 800]
 * /camera/stereo_info/cam1/rostopic: /camera/fisheye2/...
 * /camera/stereo_info/first_camera_namespace: fisheye1
 * /camera/stereo_info/input_camera_info_from_ros_params: True
 * /camera/stereo_info/process_every_nth_frame: 2
 * /camera/stereo_info/scale: 1.0
 * /camera/stereo_info/second_camera_namespace: fisheye2
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    stereo_info (image_undistort/stereo_info_node)

ROS_MASTER_URI=http://localhost:11311

process[camera/stereo_info-1]: started with pid [14432]
[ERROR] [1592563683.939323941]: Could not find K or camera intrinsics vector
[FATAL] [1592563683.939372569]: Loading of input camera parameters failed, exiting
[camera/stereo_info-1] process has died [pid 14432, exit code 1, cmd /home/ubuntu/catkin_ws/devel/lib/image_undistort/stereo_info_node raw/first/image:=fisheye1/image_raw raw/second/image:=fisheye2/image_raw __name:=stereo_info __log:=/home/ubuntu/.ros/log/4978f2ce-b21a-11ea-88e8-34de1af975b3/camera-stereo_info-1.log].
log file: /home/ubuntu/.ros/log/4978f2ce-b21a-11ea-88e8-34de1af975b3/camera-stereo_info-1*.log

**Camera internal and external parameters use camera information after calibration by Kalibr tool：**

cam0:
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.07307789354996369, -0.01624786695454266, 0.0054793688458973306,
    -0.00729763759178143]
  distortion_model: equidistant
  intrinsics: [264.78818251358086, 264.9396383111461, 426.66357941709606, 394.6197469244117]
  resolution: [848, 800]
  rostopic: /camera/fisheye1/image_raw
cam1:
  T_cn_cnm1:
  - [0.999995491891387, -0.0018850276292362385, 0.002337277848263454, -0.6313283639924419]
  - [0.0019005042088560693, 0.9999761676708998, -0.006637181176720762, -0.01075742393483845]
  - [-0.0023247108755902104, 0.0066415932619750245, 0.9999752421726688, -0.01767752105719401]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.080721126772137, -0.007771852365492558, -0.005479495403646759,
    -0.0033310908906594118]
  distortion_model: equidistant
  intrinsics: [258.99261182367377, 259.60787747453577, 418.3763242563783, 401.9743401851195]
  resolution: [848, 800]
  rostopic: /camera/fisheye2/image_raw

Does anyone know how to solve it?

**Comment by Zhangppppp** [comment]
Hi @wang-yu-yang  ,I'm having the same issue too. Were you able to solve this?
